# Site settings
title: 沫然的博客
SEOTitle: 沫然的博客
header-img: img/home-bg.jpg
email: 361131953@qq.com
description: "沫然的技术博客"
keyword: "沫然的博客"
url: "http://fengyaru.github.io"
baseurl: ""

# SNS settings
RSS: false
#weibo_username:     fengyaru
github_username:    fengyaru

# Build settings
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
anchorjs: true

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Duoshuo settings
# to the old version user, please set your own DuoShuo account in `post.html`, `keynote.html` and `about.html`
duoshuo_username: fengyaru
duoshuo_share: true                     # set to false if you want to use Comment without Sharing
# seeing the Share component is depend on Comment so we can NOT use share only.

# Analytics settings
# Baidu Analytics `head.html`
# ba_track_id: 6dcc729d6a5d5c61d7c8835eb7418d54
# Google Analytics `footer.html`
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: xpmozong.duoshuo.com

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "极客程序媛"
sidebar-avatar: /img/Ellen.jpg     # use absolute URL.

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: []